api/urls.py
from django.urls import path
# from .views import BookReviewDetailApiView,BookListAPIView
from rest_framework.routers import DefaultRouter
from api.views import BookReviewsViewSet

app_name = 'api'
router = DefaultRouter()
router.register(r'reviews', BookReviewsViewSet, basename='review')
urlpatterns = router.urls
# qolda yozilgan viewlarni pathlari
# path('reviews/',  BookListAPIView.as_view(), name='review-list'),
# path('reviews/<int:id>/', BookReviewDetailApiView.as_view(), name='review-detail')

goodreads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import landing_page, home_page

urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('home/', home_page, name='home'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls'))

]

# static filelllarni ishlatish uchun
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, ProfileView, LogoutView,ProfileUpdateView

app_name = 'users'
urlpatterns = [
    path("signup/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', ProfileUpdateView.as_view(), name='profile-edit')
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.

class CustomUser(AbstractUser):
    profile_picture = models.ImageField(default="profile-pic-MD.jpg")

users/forms.py
from django import forms
from django.core.mail import send_mail

from users.models import CustomUser


class UserCreateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', "email", "password",)

    def save(self, commit=True):
        user = super().save(commit)
        user.set_password(self.cleaned_data['password'])
        user.save()
        return user


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', "email", 'profile_picture')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control'})

users/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from users.models import CustomUser
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect
from django.views import View
from .forms import UserCreateForm, UserUpdateForm


class RegisterView(View):
    def get(self, request):
        create_forms = UserCreateForm()
        return render(request, 'users/register.html', {'form': create_forms})

    def post(self, request):
        create_form = UserCreateForm(data=request.POST)

        if create_form.is_valid():
            create_form.save()
            return redirect('users:login')
        else:
            context = {
                'form': create_form
            }
            return render(request, 'users/register.html', context)


class LoginView(View):
    def get(self, request):
        login_form = AuthenticationForm()
        return render(request, 'users/login.html', {'login_form': login_form})

    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            messages.success(request, 'You have successfully logged in.')
            return redirect('books:list')
        else:
            return render(request, 'users/login.html', {'login_form': login_form})


class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.info(request, 'You have successfully out.')
        return redirect('/')


# LoginRequiredMixin  manbu yozilgan if ni orniga ishlaydi  if not request.user.is_authenticated:return redirect(
# 'users:login')
class ProfileView(LoginRequiredMixin, View):
    def get(self, request):
        # {'user': request.user} bilan login qilingan userlarni olib odim
        # is_authenticated user login bolganmi yoqmi tekshiradi token tekshiradi
        # if not request.user.is_authenticated:
        #     return redirect('users:login')
        # else:
        # {'user': request.user} bilan login qilingan userlarni olib odim
        return render(request, 'users/profile.html', {'user': request.user})


class ProfileUpdateView(LoginRequiredMixin, View):
    def get(self, request):
        user_update_form = UserUpdateForm()
        return render(request, 'users/profile_edit.html', {'update_form': user_update_form})

    def post(self, request):
        user_update_form = UserUpdateForm(
            instance=request.user,
            data=request.POST,
            files=request.FILES
        )

        if user_update_form.is_valid():
            user_update_form.save()
            messages.success(request, 'You have successfully updated your profile')
            return redirect('users:profile')
        else:
            return render(request, 'users/profile_edit.html', {'update_form': user_update_form})

users/templates/users/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %} Login Page {% endblock %}

{% block content %}
<div style="height:80vh; width:100%" class="row d-flex justify-content-center align-items-center ">
    <div class="col-5">
<h4 class="text-center">Login</h4>
        <form method="post">
            {% csrf_token %}
<!--        crispy ni ishlatish uchun untagni chaqirish kerak     -->
            {{ login_form | crispy }}
            <button class="btn btn-primary w-100" type="submit">Submit</button>
        </form>

       <p style="color:red; margin-top:1rem">if you are not registered: <a href="{% url 'users:register' %}">register</a></p>
    </div>
</div>

{% endblock %}

users/templates/users/profile.html
  {% extends "base.html" %}


{% block title %} Profile Page
  {% endblock %}

 {% block content %}
 <div class="content-profile">
  <div class="flexs-profile">
  <img class="profile-img" src="{{user.profile_picture.url}}" alt="">
  <a class="btn btn-dark" href="{% url 'users:profile-edit' %}">Edite profile</a>
</div>
<div class="profile-body">
  <p>Username: {{user.username}}</p>
  <p>First Nme: {{user.first_name}}</p>
  <p>Last Name: {{user.last_name}}</p>
  <p>Email: {{user.email}}</p>
    <p>Joined: {{ user.date_joined |date:"M d, Y" }}</p>
  </div>
 </div>


 {% endblock %}

users/templates/users/profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
  <h1>Profile Edit</h1>

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ update_form | crispy }}
 <button type="submit">save changes</button>
</form>

{% endblock %}

users/templates/users/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} Register Page {% endblock %}

{% block content %}
<div style="height:100%; width:100%" class="row d-flex justify-content-center align-items-center ">
    <div class="col-5">
        <h4 class="text-center">Register</h4>
        <form method="post">
            {% csrf_token %}
<!--        crispy ni ishlatish uchun untagni chaqirish kerak     -->
            {{ form | crispy }}
            <button class="btn btn-primary w-100" type="submit">Submit</button>
        </form>

        <p style="color:red; margin-top:1rem">If you are registered, go to login: <a href="{% url 'users:login' %}">login</a></p>
    </div>
</div>
{% endblock %}