api/urls.py
from django.urls import path
# from .views import BookReviewDetailApiView,BookListAPIView
from rest_framework.routers import DefaultRouter
from api.views import BookReviewsViewSet

app_name = 'api'
router = DefaultRouter()
router.register(r'reviews', BookReviewsViewSet, basename='review')
urlpatterns = router.urls
# qolda yozilgan viewlarni pathlari
# path('reviews/',  BookListAPIView.as_view(), name='review-list'),
# path('reviews/<int:id>/', BookReviewDetailApiView.as_view(), name='review-detail')

books/urls.py
from django.urls import path
from .views import BooksView, BookDetailView, AddReviewForm, EditReview,ConfirmDeleteReviewView,DeleteReviewView

app_name = 'books'
urlpatterns = [
    path('', BooksView.as_view(), name='list'),
    path('<int:id>/', BookDetailView.as_view(), name='detail'),
    path('<int:id>/reviews/', AddReviewForm.as_view(), name='reviews'),
    path('<int:book_id>/reviews/<int:review_id>/edit>', EditReview.as_view(), name='edit_review'),
    path('<int:book_id>/reviews/<int:review_id>/delete/confirm>',
         ConfirmDeleteReviewView.as_view(), name='confirm-delete-review'),
    path('<int:book_id>/reviews/<int:review_id>/delete/>',
         DeleteReviewView.as_view(), name='delete-review')
]

goodreads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import landing_page, home_page

urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('home/', home_page, name='home'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls'))

]

# static filelllarni ishlatish uchun
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, ProfileView, LogoutView,ProfileUpdateView

app_name = 'users'
urlpatterns = [
    path("signup/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', ProfileUpdateView.as_view(), name='profile-edit')
]

templates/base.html
{% load static %}
{% url 'home' as home_page_url %}
{% url 'books:list' as book_list_url%}
{% url 'users:profile' as profile_page_url %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{% block title %} Goodreads Clone {% endblock %}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <link
      href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="{% static 'books/book.css' %}"
      type="text/css"
    />
    <link
      rel="stylesheet"
      href="{% static 'users/users.css' %}"
      type="text/css"
    />
  </head>
  <body>
    <div>
      <nav
        class="navbar navbar-expand-lg navbar-light mb-3"
        style="background-color: #e3f2fd"
      >
        <div class="container-fluid mx-5">
          <a class="navbar-brand" href="#">Goodreads Clone</a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a
                  {% if request.path == book_list_url %} class='active nav-link' {% endif %}
                  class="nav-link"
                  aria-current="page"
                  href="{{book_list_url}}"
                  >Books</a
                >
              </li>
              <li class="nav-item">
                <a {% if request.path == home_page_url  %} class='active nav-link' {% endif %} class="nav-link " aria-current="page"
                  href="{{home_page_url}}"
                  >Home</a
                >
              </li>
            </ul>

            <div >
              {% if request.user.is_authenticated %}
              <ul

                class="d-flex align-items-center navbar-nav"
                style="list-style: none"
              >
                <li class="nav-item dropdown d-flex">
                  <img
                    style="width: 50px; height: 50px; border-radius: 50px"
                    src="{{user.profile_picture.url}}"
                    alt=""
                  />
                  <a
                    {% if request.path == '/users/profile/'  %} class='active nav-link' {% endif %}
                    class="nav-link dropdown-toggle"
                    href="#"
                    id="navbarDropdown"
                    role="button"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                  >
                    {{request.user.username}}
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li>
                      <a   class="dropdown-item" href="{{profile_page_url}}">
                        <i  class="bx bx-child"></i>Profile</a
                      >
                    </li>
                    <li>
                      <a class="dropdown-item" href="{% url 'users:logout' %}">
                        <i class="bx bx-log-out"></i> Logout</a
                      >
                    </li>
                  </ul>
                </li>
              </ul>
              {% else %}
              <a class="btn btn-outline-primary" href="{% url 'users:login' %}"
                >Login</a
              >
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
      <div class="mx-5">
        {% if messages %} {% for message in messages %} {{message}} {% endfor %}
        {% endif %}
        <div class="container mt-5">{% block content %} {% endblock %}</div>
      </div>
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
      integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/home.html
 {% extends "base.html" %}

 {% block title %}Home{% endblock %}

 {% block content %}
 {% for review in page_objects %}
 <p>{{ review.commit}}</p>

  <div class="container posts-content">
            <div class="row">
                <div class="col-lg-6">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="media mb-3">
                                <img src="{{ review.user.profile_picture.url }}"
                                     class="d-block ui-w-40 rounded-circle" alt="">
                                <div class="media-body ml-3">
                                    <b>{{ review.user.username }}</b> rated this book {{ review.stars_given }} stars
                                    <div class="text-muted small">{{ review.created_at | date:"M d, Y" }}</div>
                                </div>
                            </div>

                            <p>
                                {{ review.commit | truncatechars:300 }}
                            </p>
                            <img class="cover-pic center" src="{{ review.book.cover_picture.url }}">
                        </div>
                    </div>
                </div>
            </div>
        </div>

 {% endfor %}
  <nav aria-label="Page navigation example">
  <ul class="pagination">
    <p class="btn btn-primary">{{page_objects.number}}</p>
     {% if page_objects.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_objects.previous_page_number }}">previous</a>
    </li>
    {% endif %}

      {% if page_objects.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}">next>></a>
    </li>
    {% endif %}
  </ul>
</nav>
 {% endblock %}

templates/landing_page.html
 {% extends "base.html" %}


 {% block content %}
   Landing Page
 {% endblock %}