api/urls.py
from django.urls import path
# from .views import BookReviewDetailApiView,BookListAPIView
from rest_framework.routers import DefaultRouter
from api.views import BookReviewsViewSet

app_name = 'api'
router = DefaultRouter()
router.register(r'reviews', BookReviewsViewSet, basename='review')
urlpatterns = router.urls
# qolda yozilgan viewlarni pathlari
# path('reviews/',  BookListAPIView.as_view(), name='review-list'),
# path('reviews/<int:id>/', BookReviewDetailApiView.as_view(), name='review-detail')

books/urls.py
from django.urls import path
from .views import BooksView, BookDetailView, AddReviewForm, EditReview,ConfirmDeleteReviewView,DeleteReviewView

app_name = 'books'
urlpatterns = [
    path('', BooksView.as_view(), name='list'),
    path('<int:id>/', BookDetailView.as_view(), name='detail'),
    path('<int:id>/reviews/', AddReviewForm.as_view(), name='reviews'),
    path('<int:book_id>/reviews/<int:review_id>/edit>', EditReview.as_view(), name='edit_review'),
    path('<int:book_id>/reviews/<int:review_id>/delete/confirm>',
         ConfirmDeleteReviewView.as_view(), name='confirm-delete-review'),
    path('<int:book_id>/reviews/<int:review_id>/delete/>',
         DeleteReviewView.as_view(), name='delete-review')
]

goodreads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import landing_page, home_page

urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('home/', home_page, name='home'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls'))

]

# static filelllarni ishlatish uchun
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from users.models import CustomUser
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils import timezone


# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    isbn = models.CharField(max_length=17)
    cover_picture = models.ImageField(default="default_image.png")

    def __str__(self):
        return self.title


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    bio = models.TextField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class BookAuthor(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.book} by {self.author.last_name} {self.author.first_name}"


class BookReview(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    commit = models.TextField()
    # commenda qachon qoldirganligini vaqtini saqlaydi
    starts_given = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.user.username} by {self.book}"

books/forms.py
from django import forms

from books.models import BookReview


class BookReviewForm(forms.ModelForm):
    starts_given = forms.IntegerField(min_value=1, max_value=5)

    class Meta:
        model = BookReview
        fields = ('starts_given', 'commit')

books/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View

from .forms import BookReviewForm
from .models import Book
from .models import BookReview
from django.views.generic import ListView


# Create your views here.
# generic get qilish uchun ishlatiladi
# class BooksView(ListView):
#     template_name = 'books/list.html'
#     queryset = Book.objects.all()
#     context_object_name = "books"
# paginate_by = 2


class BooksView(LoginRequiredMixin, View):
    def get(self, request):
        books = Book.objects.all().order_by('id')
        search_query = request.GET.get('q', '')
        if search_query:
            books = books.filter(title__icontains=search_query)
        page_size = request.GET.get('page_size', 2)
        paginator = Paginator(books, page_size)
        page_number = request.GET.get('page', 1)
        page_obj = paginator.get_page(page_number)

        return render(request, 'books/list.html', {'page_obj': page_obj, 'search_query': search_query})


class BookDetailView(View):
    def get(self, request, id):
        book = Book.objects.get(id=id)
        review_form = BookReviewForm()
        return render(request, 'books/detail.html', {'book': book, 'review_form': review_form})


class AddReviewForm(LoginRequiredMixin, View):
    def post(self, request, id):
        book = Book.objects.get(id=id)
        review_form = BookReviewForm(data=request.POST)

        if review_form.is_valid():
            # review create qilish
            BookReview.objects.create(
                # book  book = Book.object.get(id=id) dan kelgan book
                book=book,
                # user esa requestdan kelgan user login qilingan userlarni tekshirish uchun {LoginRequiredMixin}
                user=request.user,
                #  bu ikalasi form dan kelagan
                starts_given=review_form.cleaned_data['starts_given'],
                commit=review_form.cleaned_data['commit']
            )
            return redirect(reverse('books:detail', kwargs={'id': book.id}))

        return render(request, 'books/detail.html', {'book': book, 'review_form': review_form})


class EditReview(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        # book bilan review ni get qilib olngan bu 2 ta codeda
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        # editeda isinstance beriladi chunki qaysi review edite qilishmizni bildirish uchun
        review_form = BookReviewForm(instance=review)
        return render(request, 'books/edit_review.html', {'book': book, 'review': review, 'review_form': review_form})

    def post(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        review_form = BookReviewForm(instance=review, data=request.POST)

        if review_form.is_valid():
            review_form.save()
            return redirect(reverse('books:detail', kwargs={'id': book.id}))
        else:
            return render(request, 'books/edit_review.html', {'book': book, 'review': review, 'review_form': review_form})


class ConfirmDeleteReviewView(LoginRequiredMixin, View):

    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        return render(request, 'books/confirm_delete_review.html', {'book': book, 'review': review})


class DeleteReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        review.delete()
        messages.success(request, 'You have successfully delete this review')
        return redirect(reverse('books:detail', kwargs={'id': book.id}))

books/templates/books/confirm_delete_review.html
{% extends "base.html" %}
{% block title %} Delete {% endblock %}


{% block content %}
 <dev>
     <h4><b>Book:</b> {{book.title}}</h4>
     <p><b>Comment:</b> {{review.commit}}</p>
     <a class="btn btn-outline-danger" href="{% url 'books:delete-review' book.id review.id %}">Yes</a>
     <a class="btn btn-outline-primary" href="{% url 'books:detail' book.id %}">No</a>


 </dev>
{% endblock %}

books/templates/books/detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} Book Detail Page {% endblock %}

{% block content %}
<div class="row mb-2">
    <div class="col-2">
        <img class="bg-img" src="{{ book.cover_picture.url }}" alt="">
    </div>
    <div class="col-6">
        <h3 style="color:red">
            {{ book.title }}
        </h3>
        <span class="fst-italic">
            Authored by
            {% for book_author in book.bookauthor_set.all %}
            {% if forloop.last %}
               {{book_author.author}}
            {% else %}
               {{book_author.author}},
            {% endif %}

            {% endfor %}
        </span>
        <p style="width:50%;color:blue">
            {{ book.description }}
        </p>
    </div>
</div>

<div class="row mb-3">
    <div class="col-6">

        <form method="post" action="{% url 'books:reviews' book.id %}">
            {% csrf_token %}
            <!--        crispy ni ishlatish uchun untagni chaqirish kerak     -->
            {{ review_form | crispy }}
            <button class="btn btn-success">Add review</button>
        </form>

    </div>
</div>
{% if book.bookreview_set.exists %}
<h4>Reviews</h4>
<hr>
{% for review in book.bookreview_set.all %}
<div class="row mb-3 ">
    <div class="col-1 ">
        <img class="small-profile-pic" src="{{ review.user.profile_picture.url }}" alt="404 not found">
    </div>
    <div class="col-7 ">
        <b> {{review.user.username}}</b> rated in {{review.starts_given}} <span class="fw-lighter">{{ review.created_at }}</span>
        {% if review.user == request.user %}
            <a href="{% url 'books:edit_review' book.id review.id %}"><i class='bx bxs-pencil'></i></a>
            <a href="{% url 'books:confirm-delete-review' book.id review.id %}"><i class='bx bx-trash-alt'></i></a>
        {% endif  %}
        <p class="mt-2 font-monospace">{{ review.commit }}</p>
    </div>
</div>
{% endfor %}
{% endif %}
{% endblock %}

books/templates/books/edit_review.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} Edite {% endblock %}

{% block content %}
<h1>Edite Page</h1>

        <form method="post" action="{% url 'books:edit_review' book.id review.id %}">
            {% csrf_token %}
            <!--        crispy ni ishlatish uchun untagni chaqirish kerak     -->
            {{ review_form | crispy }}
            <button class="btn btn-success">Add review</button>
        </form>

{% endblock %}

books/templates/books/list.html
{% extends "base.html" %}
{% block title %}Books{% endblock %}


{% block content %}
<h3>Books</h3>

<div class="row mb-3">
  <div class="col-4">
    <form  method="get" class="d-flex">
     <input class="form-control me-2" type="text" placeholder="Search" name="q" value="{{ search_query }}">
    <button class="btn btn-success">Search</button>
    </form>
  </div>

</div>
{% if page_obj %}
{% for book in page_obj.object_list %}
<div class="row mb-3">
  <div class="col-2">
    <img class="bg-img" src="{{ book.cover_picture.url }}" alt="" />
  </div>
  <div class="col-6">
    <a href="{% url 'books:detail' book.id %}">{{book.title}}</a>
    <p>{{book.description}}</p>
  </div>
</div>
{% endfor %}
<nav aria-label="Page navigation example">
  <ul class="pagination">
    <p class="btn btn-primary">{{page_obj.number}}</p>
     {% if page_obj.has_previous %}
    <li class="page-item">
      <a
        class="page-link"
        href="{% url 'books:list' %}?page={{ page_obj.previous_page_number }}"
      >
      previous</a
      >
    </li>
    {% endif %} {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="{% url 'books:list' %}?page={{ page_obj.next_page_number }}"
        >next>></a
      >
    </li>
    {% endif %}
  </ul>
</nav>
{% else %}
 No books found.
{% endif %}
{% endblock %}